         # MySQL.  Versions 4.1 and 5.0 are recommended.
         #
         # Install the MySQL driver:
         #   gem install mysql2
         #
         # And be sure to use new-style password hashing:
         #   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


         development:
           adapter: mysql
           database: sample_development
           host: localhost
           peoplename: root
           password:
           encoding: utf8

         production:
          adapter: mysql
          database: sample_production
          host: localhost
          peoplename: root
          password:
          encoding: utf8

         test:
           adapter: mysql
           database: sample_test
           host: localhost
           peoplename: root
           password: 
           encoding: utf8
